export const TOGGLE_TYPE = "TOGGLE_TYPE" 
export const LOAD_SERVICE = "LOAD_SERVICE" 
export const LOAD_CLASSEUR = "LOAD_CLASSEUR" 


export const EDIT_PROFILE_ALL = "EDIT_PROFILE_ALL" 
export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT" 
export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT" 
export const LOAD_USER_DETAILS = "LOAD_USER_DETAILS" 
export const SELECT_ACCOUNT = "SELECT_ACCOUNT" 
export const GET_ACCOUNT = "GET_ACCOUNT" 